dist: xenial
language: csharp
solution: Customers.Pn.sln
mono: none
dotnet: 2.2
services:
  - mysql
script:
  - dotnet restore eFormAPI/Plugins/Customers.Pn/Customers.Pn.sln
  - dotnet build eFormAPI/Plugins/Customers.Pn/Customers.Pn.sln
  - dotnet test -v n eFormAPI/Plugins/Customers.Pn/Customers.Pn.Test/Customers.Pn.Test.csproj
  - cd ../..
  - git clone --depth=50 --branch=master https://github.com/microting/eform-angular-frontend.git microting/eform-angular-frontend
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/src/app/plugins/modules/customers-pn microting/eform-angular-frontend/eform-client/src/app/plugins/modules/customers-pn
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/e2e/Tests/customer-settings microting/eform-angular-frontend/eform-client/e2e/Tests/customer-settings
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/e2e/Tests/customer-general microting/eform-angular-frontend/eform-client/e2e/Tests/customer-general
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/wdio-headless-plugin-step2.conf.js microting/eform-angular-frontend/eform-client/wdio-headless-plugin-step2.conf.js
  - cd microting/eform-angular-frontend 
  - dotnet restore -v q eFormAPI/eFormAPI.sln > dotnet_log 2>&1 &
  - dotnet build eFormAPI/eFormAPI.sln > dotnet_log 2>&1 &
  - cd ../..
  - mkdir -p microting/eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins
  - cp -av microting/eform-angular-basecustomer-plugin/eFormAPI/eFormAPI.Web/Plugins/Customers microting/eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins/Customers
  - cd microting/eform-angular-frontend
  - cd eform-client && npm install
  - ../../eform-angular-basecustomer-plugin/testinginstallpn.sh
  - npm start &
  - sleep 40
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
  - sleep 40
  - npm run testheadless
  - sleep 40
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
  - sleep 40
  - npm run testheadlessplugin
