dist: bionic
language: csharp
solution: Customers.Pn.sln
mono: none
dotnet: 2.2
addons:
  chrome: stable
services:
  - mysql
intstall:
  - nvm install 12.16.2
  - nvm use 12.16.2
  - pip install --user awscli
  - echo 'deb http://www.rabbitmq.com/debian/ testing main' | sudo tee /etc/apt/sources.list.d/rabbitmq.list
  - wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rabbitmq-server
  - sudo systemctl enable rabbitmq-server
  - sudo systemctl start rabbitmq-server
  - sudo rabbitmqctl add_user admin password 
  - sudo rabbitmqctl set_user_tags admin administrator
  - sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  - sudo rabbitmq-plugins enable rabbitmq_management	
  - wget http://localhost:15672/cli/rabbitmqadmin
  - chmod +x rabbitmqadmin
  - ./rabbitmqadmin declare queue name=eformsdk-input durable=true
  - ./rabbitmqadmin declare queue name=eform-angular-basecustomer-plugin durable=true
script:
  - dotnet restore eFormAPI/Plugins/Customers.Pn/Customers.Pn.sln
  - dotnet build eFormAPI/Plugins/Customers.Pn/Customers.Pn.sln
  - dotnet test -v n eFormAPI/Plugins/Customers.Pn/Customers.Pn.Test/Customers.Pn.Test.csproj
  - cd ../..
  - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/microting/eform-angular-frontend.git microting/eform-angular-frontend
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/src/app/plugins/modules/customers-pn microting/eform-angular-frontend/eform-client/src/app/plugins/modules/customers-pn
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/e2e/Tests/customer-settings microting/eform-angular-frontend/eform-client/e2e/Tests/customer-settings
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/e2e/Tests/customer-general microting/eform-angular-frontend/eform-client/e2e/Tests/customer-general
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/e2e/Assets/ microting/eform-angular-frontend/eform-client/e2e/Assets
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/e2e/Page\ objects/Customers microting/eform-angular-frontend/eform-client/e2e/Page\ objects/Customers
  - cp -av microting/eform-angular-basecustomer-plugin/eform-client/wdio-headless-plugin-step2.conf.js microting/eform-angular-frontend/eform-client/wdio-headless-plugin-step2.conf.js
  - cd microting/eform-angular-frontend 
  - dotnet restore -v q eFormAPI/eFormAPI.sln > dotnet_log 2>&1 &
  - dotnet build eFormAPI/eFormAPI.sln > dotnet_log 2>&1 &
  - cd ../..
  - mkdir -p microting/eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins
  - cp -av microting/eform-angular-basecustomer-plugin/eFormAPI/eFormAPI.Web/Plugins/Customers microting/eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins/Customers
  - cd microting/eform-angular-frontend
  - mkdir -p /home/travis/build/microting/eform-angular-frontend/eform-client/errorShots
  - cd eform-client && npm install
  - ../../eform-angular-basecustomer-plugin/testinginstallpn.sh
  - npm start &
  - sleep 75
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
  - sleep 75
  - npm run testheadless
  - npm run testheadlessplugin
  - touch ~/.aws/config || true
  - echo "[default]" >> ~/.aws/config || true
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config || true
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config || true
  - echo "region=$AWS_DEFAULT_REGION" >> ~/.aws/config || true
  - aws s3 sync errorShots/ s3://$S3_STORAGE_FOLDER/Customers/$TRAVIS_BUILD_NUMBER || true
  - aws s3 cp dotnet_log s3://$S3_STORAGE_FOLDER/Customers/$TRAVIS_BUILD_NUMBER/dotnet_log || true
